# fly.toml app configuration file generated for bloom-hq on 2023-08-23T18:16:26-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bloom-hq"
primary_region = "den"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
