import Head from "next/head";
import { Inter } from "next/font/google";
import prisma from "../../lib/prisma";

const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps = async () => {
  const posts = await prisma.post.findMany({
    select: {
      id: true,
      title: true,
      description: true,
    },
  });
  return { props: { posts } };
};

interface Post {
  id: string;
  title: string;
  description: string;
}

export default function Home({ posts }: { posts: Post[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <p>Get started by editing&nbsp;</p>
        <div>
          {posts &&
            posts.map((post) => (
              <div key={post.id}>
                <h2>{post.title}</h2>
                <p>{post.description}</p>
              </div>
            ))}
        </div>
      </main>
    </>
  );
}
